server:
  port: 8080

spring:
  session:
    store-type: none
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018/ship_doc_db?authSource=admin

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ship_admin_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  servlet:
    multipart:
      max-file-size: 100MB      # 单个文件最大 100MB (默认是 1MB)
      max-request-size: 100MB   # 整个请求最大 100MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted

